SCMOD-8516: disbable tls 1.1
caf-archive/opensuse-java8-images pull request #14
Opened 2020-03-31 17:00 UTC by gaana-vishwnath

2020-03-31 17:39 UTC, dermot-hardy approved these changes
You need to update the release notes.  We need to get back into the practice of doing that.  Apart from that this change looks OK.  Have you confirmed that no further ciphers need to be disabled?

2020-04-01 08:54 UTC, michael-bryson commented on release-notes-2.1.0.md
> +- **SCMOD-8516**: Extend the TLS/SSL cipher hardening of the Java base images to disallow tlsv1 and tlsv1.1
tls should be uppercase

2020-04-01 09:58 UTC, gaana-vishwnath commented
> You need to update the release notes. We need to get back into the practice of doing that. Apart from that this change looks OK. Have you confirmed that no further ciphers need to be disabled?

Updated the release notes. I used the https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility link to check and didnt find anything for tlsv1.1 but found in https://tools.ietf.org/html/rfc4346#page-53 And I am not sure of any other links which has the comprehensive cipher list.

2020-04-01 13:36 UTC, dermot-hardy requested changes

2020-04-01 13:36 UTC, dermot-hardy commented on release-notes-2.1.0.md
> +- **SCMOD-8516**: Extend the TLS/SSL cipher hardening of the Java base images to disallow TLSv1.1
This is a breaking change so it will need to be listed as such in the release notes and the version number should be updated appropriately.

2020-04-01 13:36 UTC, dermot-hardy commented on src/main/docker/disableWeakTlsAlgorithms.patch
> +#Cipher found for TLSv1.1 in https://tools.ietf.org/html/rfc4346#page-53
Remove this line comment.  (Just keep it in the Jira or in the PR notes)

2020-04-02 19:49 UTC, dermot-hardy approved these changes

2020-04-03 09:16 UTC, merged

2020-04-03 09:18 UTC, andyreidz commented
It looks like Dermot wanted Rob to review.

![image](https://user-images.githubusercontent.com/18459684/78344508-65197c00-7594-11ea-9142-ba1671c6aa6a.png)

2020-04-03 16:36 UTC, rob-duewer reviewed
Sure would have been nice to provide a whitelist of only the ones that are OK instead of trying to disallow all those that aren't; huh?

Anyhow, you haven't locked it down nearly far enough.  Remember, you're aiming for the only those suites in the "intermediate" compatibility list (https://wiki.mozilla.org/Security/Server_Side_TLS)

So I'll cut to the chase a little, since we've already done this homework elsewhere to ensure server side restrictions are evenly applied.  Of the 11 suites in that list, only 6x are going to be permitted for use in the J8 implementation.  (3x of them are TLS 1.3 only.  2x of them use the chacha stream cipher.  Neither available in J8).  And the conversion to the list for j8's naming model is:

TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256

**Everything** else, including comm models except TLS1.2 (SSLv3,TLSv1,TLSv1.2) , needs to be excluded.  That list is gonna be real long (https://docs.oracle.com/javase/8/docs/technotes/guides/security/SunProviders.html, looking at the DefaultEnabled and DefaultDisabled lists.)

But there are a couple shortcuts, so you don't have to provide the full explicit list.  (Although I've got to wonder why Java8 didn't implement regex matching for this or use the standard names.  We'll just chalk that up to its age. :) )

In fact, it looks like you're mostly duplicating what is caught and disabled by those.   Take a look at https://www.java.com/en/configure_crypto.html, in the Disable TLS 1.0 and TLS 1.1 section.  See in both their (and your proposed modification), how they're excluding RC4, DES, MD5withRSA, 3DES_EDE_CBC, anon, NULL?  (In addition to extra restrictions on Diffe-Helman key sizes and EC key sizes? (DH keySize < 1024 and  EC keySize < 224).

That means your explicit exclusion of those that fall into those portions are redundant.  I don't think it hurts, but as a practice; you shouldn't be double listing them...

Again to cut to the chase, you should only have to extend out the list with those that are not normally excluded using the default shortcut nomenclature, but need to be.  You might be able to shrink this explicit list some more too, since I think you could successfully everything with DSS and CBC too.  But you'll have to do that homework, since I'm not sure exactly of the short name portions that are acceptable.

Anyhow, a little working backward makes the change you need to make here something like:

jdk.tls.disabledAlgorithms=SSLv3, RC4, DES, MD5withRSA, DH keySize < 1024, \
EC keySize < 224, 3DES_EDE_CBC, anon, NULL, \
TLSv1, TLSv1.1, \
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, \
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, \
TLS_RSA_WITH_AES_256_CBC_SHA256, \
TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384, \
TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384, \
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256, \
TLS_DHE_DSS_WITH_AES_256_CBC_SHA256, \
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, \
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, \
TLS_RSA_WITH_AES_256_CBC_SHA, \
TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA, \
TLS_ECDH_RSA_WITH_AES_256_CBC_SHA, \
TLS_DHE_RSA_WITH_AES_256_CBC_SHA, \
TLS_DHE_DSS_WITH_AES_256_CBC_SHA, \
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, \
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, \
TLS_RSA_WITH_AES_128_CBC_SHA256, \
TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256, \
TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256, \
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, \
TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, \
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, \
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, \
TLS_RSA_WITH_AES_128_CBC_SHA, \
TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA, \
TLS_ECDH_RSA_WITH_AES_128_CBC_SHA, \
TLS_DHE_RSA_WITH_AES_128_CBC_SHA, \
TLS_DHE_DSS_WITH_AES_128_CBC_SHA, \
TLS_ECDHE_ECDSA_WITH_RC4_128_SHA, \
TLS_ECDHE_RSA_WITH_RC4_128_SHA, \
SSL_RSA_WITH_RC4_128_SHA, \
TLS_ECDH_ECDSA_WITH_RC4_128_SHA, \
TLS_ECDH_RSA_WITH_RC4_128_SHA, \
TLS_RSA_WITH_AES_256_GCM_SHA384, \
TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384, \
TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384, \
TLS_DHE_DSS_WITH_AES_256_GCM_SHA384, \
TLS_RSA_WITH_AES_128_GCM_SHA256, \
TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256, \
TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256, \
TLS_DHE_DSS_WITH_AES_128_GCM_SHA256, \
TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA, \
TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA, \
SSL_RSA_WITH_3DES_EDE_CBC_SHA, \
TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA, \
TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA, \
SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA, \
SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA, \
SSL_RSA_WITH_RC4_128_MD5, \
TLS_EMPTY_RENEGOTIATION_INFO_SCSV